let students = [{"id":1,"name":"Kingston","email":"kfatharly0@amazon.co.uk","salary":"Krona"},
{"id":2,"name":"Sharia","email":"sbullin1@cyberchimps.com","salary":"Euro"},
{"id":3,"name":"Jeannine","email":"jpenzer2@mac.com","salary":"Franc"},
{"id":4,"name":"Rourke","email":"rleestut3@europa.eu","salary":"Rupiah"},
{"id":5,"name":"Devin","email":"dsibthorpe4@discovery.com","salary":"Som"},
{"id":6,"name":"Mireille","email":"mtoe5@wsj.com","salary":"Peso"},
{"id":7,"name":"Kirstin","email":"kmogridge6@cbslocal.com","salary":"Euro"},
{"id":8,"name":"Hasty","email":"hbendan7@oaic.gov.au","salary":"Euro"},
{"id":9,"name":"Neel","email":"nthynne8@printfriendly.com","salary":"Zloty"},
{"id":10,"name":"Marley","email":"maddenbrooke9@pcworld.com","salary":"Rupiah"},
{"id":11,"name":"Chelsy","email":"cjanewaya@dailymotion.com","salary":"Koruna"},
{"id":12,"name":"Merralee","email":"mjasperb@google.pl","salary":"Krona"},
{"id":13,"name":"Xenia","email":"xturtonc@squarespace.com","salary":"Ruble"},
{"id":14,"name":"Sammie","email":"skarpmand@example.com","salary":"Quetzal"},
{"id":15,"name":"Burr","email":"bbrotherheade@abc.net.au","salary":"Euro"},
{"id":16,"name":"Rachelle","email":"rrozyckif@mac.com","salary":"Yuan Renminbi"},
{"id":17,"name":"Shelton","email":"sstapleyg@bloglovin.com","salary":"Euro"},
{"id":18,"name":"Elvina","email":"eoshielsh@npr.org","salary":"Euro"},
{"id":19,"name":"Roselle","email":"ryoskowitzi@vinaora.com","salary":"Hryvnia"},
{"id":20,"name":"Felicia","email":"fabernethyj@posterous.com","salary":"Yuan Renminbi"},
{"id":21,"name":"Lira","email":"lfrankomk@naver.com","salary":"Real"},
{"id":22,"name":"Marguerite","email":"mlehrerl@kickstarter.com","salary":"Peso"},
{"id":23,"name":"Margi","email":"mkewleym@stanford.edu","salary":"Kwacha"},
{"id":24,"name":"Oralle","email":"owhelptonn@bandcamp.com","salary":"Yuan Renminbi"},
{"id":25,"name":"Kitti","email":"kfriseo@shutterfly.com","salary":"Peso"},
{"id":26,"name":"Carmella","email":"calawayp@berkeley.edu","salary":"Yuan Renminbi"},
{"id":27,"name":"Misty","email":"mangearq@t.co","salary":"Peso"},
{"id":28,"name":"Pattie","email":"plippingwellr@prweb.com","salary":"Manat"},
{"id":29,"name":"Tammara","email":"tgiggs@narod.ru","salary":"Yuan Renminbi"},
{"id":30,"name":"Larisa","email":"lruppelint@miibeian.gov.cn","salary":"Euro"},
{"id":31,"name":"Bartholomeus","email":"bisgateu@soup.io","salary":"Euro"},
{"id":32,"name":"Ira","email":"iloftyv@aol.com","salary":"Peso"},
{"id":33,"name":"Kain","email":"kyeomanw@flavors.me","salary":"Euro"},
{"id":34,"name":"Freddi","email":"ffiremanx@nps.gov","salary":"Yuan Renminbi"},
{"id":35,"name":"Randell","email":"rheadechy@qq.com","salary":"Peso"},
{"id":36,"name":"Daveta","email":"delcumz@w3.org","salary":"Sol"},
{"id":37,"name":"Layne","email":"lmussared10@phoca.cz","salary":"Zloty"},
{"id":38,"name":"Maribelle","email":"mkyttor11@tripadvisor.com","salary":"Sol"},
{"id":39,"name":"Kacy","email":"khards12@msu.edu","salary":"Peso"},
{"id":40,"name":"Wilton","email":"wmcalindon13@goo.gl","salary":"Euro"},
{"id":41,"name":"Lambert","email":"lthroughton14@vinaora.com","salary":"Euro"},
{"id":42,"name":"Angelique","email":"awinkworth15@so-net.ne.jp","salary":"Yuan Renminbi"},
{"id":43,"name":"Asia","email":"adrake16@cdbaby.com","salary":"Quetzal"},
{"id":44,"name":"Murial","email":"mjanaway17@jigsy.com","salary":"Dollar"},
{"id":45,"name":"Rivy","email":"rbonaire18@state.gov","salary":"Ruble"},
{"id":46,"name":"Dorie","email":"dbernardini19@tinyurl.com","salary":"Ruble"},
{"id":47,"name":"Lucio","email":"lgallatly1a@gravatar.com","salary":"Sol"},
{"id":48,"name":"Ethelda","email":"enason1b@sogou.com","salary":"Rupiah"},
{"id":49,"name":"Gil","email":"gcettell1c@netlog.com","salary":"Peso"},
{"id":50,"name":"Kayne","email":"kskedge1d@icq.com","salary":"Yuan Renminbi"},
{"id":51,"name":"Zorine","email":"zhaile1e@bing.com","salary":"Dollar"},
{"id":52,"name":"Jedediah","email":"jtuffell1f@shutterfly.com","salary":"Real"},
{"id":53,"name":"Vinny","email":"vingree1g@list-manage.com","salary":"Baht"},
{"id":54,"name":"Ania","email":"aseiter1h@hubpages.com","salary":"Rupiah"},
{"id":55,"name":"Shirleen","email":"sswinley1i@bing.com","salary":"Baht"},
{"id":56,"name":"Obed","email":"orayne1j@linkedin.com","salary":"Lev"},
{"id":57,"name":"Link","email":"lchisolm1k@theglobeandmail.com","salary":"Koruna"},
{"id":58,"name":"Al","email":"aribeiro1l@wired.com","salary":"Peso"},
{"id":59,"name":"Brady","email":"bkunzelmann1m@ameblo.jp","salary":"Peso"},
{"id":60,"name":"Jaynell","email":"jseyffert1n@flavors.me","salary":"Ruble"},
{"id":61,"name":"Drugi","email":"dkalisz1o@jugem.jp","salary":"Yuan Renminbi"},
{"id":62,"name":"Craggy","email":"cwrenn1p@squarespace.com","salary":"Dollar"},
{"id":63,"name":"Marcella","email":"mgamlyn1q@nationalgeographic.com","salary":"Peso"},
{"id":64,"name":"Gilburt","email":"gyarrell1r@constantcontact.com","salary":"Ruble"},
{"id":65,"name":"Melonie","email":"mmoden1s@simplemachines.org","salary":"Peso"},
{"id":66,"name":"Werner","email":"wroome1t@cdbaby.com","salary":"Yuan Renminbi"},
{"id":67,"name":"Emiline","email":"epool1u@woothemes.com","salary":"Peso"},
{"id":68,"name":"Adina","email":"acarreyette1v@java.com","salary":"Peso"},
{"id":69,"name":"Iggy","email":"iabden1w@tamu.edu","salary":"Dinar"},
{"id":70,"name":"Nobie","email":"nilieve1x@biblegateway.com","salary":"Franc"},
{"id":71,"name":"Bobbi","email":"bdunican1y@discovery.com","salary":"Euro"},
{"id":72,"name":"Korney","email":"kbale1z@jigsy.com","salary":"Koruna"},
{"id":73,"name":"Lynnette","email":"lfurneaux20@g.co","salary":"Rupiah"},
{"id":74,"name":"Wrennie","email":"wfarquar21@discovery.com","salary":"Yuan Renminbi"},
{"id":75,"name":"Honey","email":"hhughesdon22@ycombinator.com","salary":"Rupiah"},
{"id":76,"name":"Durand","email":"divanisov23@nationalgeographic.com","salary":"Real"},
{"id":77,"name":"Riobard","email":"ringarfill24@drupal.org","salary":"Peso"},
{"id":78,"name":"Monah","email":"mwildes25@blogspot.com","salary":"Real"},
{"id":79,"name":"Othilia","email":"osharville26@artisteer.com","salary":"Sol"},
{"id":80,"name":"Kara-lynn","email":"kscones27@cocolog-nifty.com","salary":"Rupiah"},
{"id":81,"name":"Lynnet","email":"lrickhuss28@vinaora.com","salary":"Sol"},
{"id":82,"name":"Dannye","email":"dlemaitre29@ox.ac.uk","salary":"Real"},
{"id":83,"name":"Udale","email":"udenerley2a@sogou.com","salary":"Manat"},
{"id":84,"name":"Cassie","email":"crowberry2b@linkedin.com","salary":"Yen"},
{"id":85,"name":"Susana","email":"stunnick2c@ca.gov","salary":"Yuan Renminbi"},
{"id":86,"name":"Trever","email":"tduffie2d@ycombinator.com","salary":"Yuan Renminbi"},
{"id":87,"name":"Rasla","email":"rnafziger2e@nature.com","salary":"Zloty"},
{"id":88,"name":"Burk","email":"bbrolan2f@tiny.cc","salary":"Rupiah"},
{"id":89,"name":"Etienne","email":"evenn2g@squidoo.com","salary":"Peso"},
{"id":90,"name":"Tiebout","email":"tgrason2h@wordpress.org","salary":"Rupiah"},
{"id":91,"name":"Lannie","email":"laldham2i@list-manage.com","salary":"Yuan Renminbi"},
{"id":92,"name":"Hester","email":"hchevins2j@mit.edu","salary":"Shekel"},
{"id":93,"name":"Roselia","email":"rdoldon2k@mapy.cz","salary":"Yuan Renminbi"},
{"id":94,"name":"Elsinore","email":"eanthes2l@artisteer.com","salary":"Naira"},
{"id":95,"name":"Rebeca","email":"rbraitling2m@histats.com","salary":"Euro"},
{"id":96,"name":"Gabe","email":"gmainds2n@nationalgeographic.com","salary":"Yen"},
{"id":97,"name":"Sarette","email":"soxbe2o@drupal.org","salary":"Yen"},
{"id":98,"name":"Maynord","email":"mcabane2p@symantec.com","salary":"Yuan Renminbi"},
{"id":99,"name":"Stephanus","email":"smattheis2q@dagondesign.com","salary":"Yuan Renminbi"},
{"id":100,"name":"Bab","email":"bocurrine2r@zimbio.com","salary":"Peso"},
{"id":101,"name":"Nickolas","email":"nwarbey2s@jimdo.com","salary":"Dollar"},
{"id":102,"name":"Eugen","email":"estilwell2t@livejournal.com","salary":"Marka"},
{"id":103,"name":"Jacynth","email":"jdanilovitch2u@youku.com","salary":"Peso"},
{"id":104,"name":"Lil","email":"lmilmoe2v@nhs.uk","salary":"Real"},
{"id":105,"name":"Maris","email":"mlefloch2w@statcounter.com","salary":"Real"},
{"id":106,"name":"Dee","email":"dvassie2x@livejournal.com","salary":"Euro"},
{"id":107,"name":"Haley","email":"hcozby2y@ifeng.com","salary":"Peso"},
{"id":108,"name":"Tony","email":"tdunthorn2z@walmart.com","salary":"Hryvnia"},
{"id":109,"name":"Hersch","email":"hkeiley30@mlb.com","salary":"Ruble"},
{"id":110,"name":"Jillana","email":"jbusch31@weather.com","salary":"Peso"},
{"id":111,"name":"Dione","email":"dvooght32@paginegialle.it","salary":"Rupiah"},
{"id":112,"name":"Annmarie","email":"aodoran33@cbsnews.com","salary":"Ruble"},
{"id":113,"name":"Britni","email":"bsibbering34@dagondesign.com","salary":"Real"},
{"id":114,"name":"Germaine","email":"gbea35@youtube.com","salary":"Baht"},
{"id":115,"name":"Jan","email":"jraubheim36@cyberchimps.com","salary":"Dinar"},
{"id":116,"name":"Guido","email":"gulyatt37@whitehouse.gov","salary":"Rupiah"},
{"id":117,"name":"Tait","email":"tkorda38@fc2.com","salary":"Yuan Renminbi"},
{"id":118,"name":"Guenna","email":"gkettlesing39@archive.org","salary":"Dollar"},
{"id":119,"name":"Geoff","email":"gboulds3a@youtube.com","salary":"Euro"},
{"id":120,"name":"Ginelle","email":"gmellings3b@dropbox.com","salary":"Yuan Renminbi"},
{"id":121,"name":"Libby","email":"lorcas3c@senate.gov","salary":"Yuan Renminbi"},
{"id":122,"name":"Chan","email":"cgut3d@bloomberg.com","salary":"Dollar"},
{"id":123,"name":"Wadsworth","email":"waltamirano3e@infoseek.co.jp","salary":"Ruble"},
{"id":124,"name":"Shaw","email":"sdevile3f@amazon.co.jp","salary":"Baht"},
{"id":125,"name":"Lida","email":"loneill3g@gmpg.org","salary":"Yuan Renminbi"},
{"id":126,"name":"Nahum","email":"nkiln3h@salon.com","salary":"Peso"},
{"id":127,"name":"Felipa","email":"fvertey3i@hugedomains.com","salary":"Yuan Renminbi"},
{"id":128,"name":"Kylila","email":"kswithenby3j@myspace.com","salary":"Lempira"},
{"id":129,"name":"Lyndsey","email":"lciccetti3k@tamu.edu","salary":"Krone"},
{"id":130,"name":"Amelina","email":"acaccavale3l@ask.com","salary":"Yuan Renminbi"},
{"id":131,"name":"Bellanca","email":"bracher3m@google.com.br","salary":"Rupiah"},
{"id":132,"name":"Giustino","email":"gfagge3n@dyndns.org","salary":"Peso"},
{"id":133,"name":"Ralf","email":"rpegden3o@blinklist.com","salary":"Krona"},
{"id":134,"name":"Gianna","email":"gkmietsch3p@t-online.de","salary":"Krona"},
{"id":135,"name":"Benedick","email":"bjozsa3q@cmu.edu","salary":"Rupiah"},
{"id":136,"name":"Friedrich","email":"fguilayn3r@jiathis.com","salary":"Kwacha"},
{"id":137,"name":"Lyell","email":"llumm3s@deviantart.com","salary":"Yuan Renminbi"},
{"id":138,"name":"Blane","email":"bcovelle3t@ebay.com","salary":"Shekel"},
{"id":139,"name":"Delila","email":"dvalois3u@google.com.au","salary":"Rupiah"},
{"id":140,"name":"Maire","email":"mleghorn3v@dion.ne.jp","salary":"Lev"},
{"id":141,"name":"Adrian","email":"adenford3w@nih.gov","salary":"Sol"},
{"id":142,"name":"Rochette","email":"rmaybey3x@about.com","salary":"Yuan Renminbi"},
{"id":143,"name":"Aubrie","email":"amackerness3y@apple.com","salary":"Peso"},
{"id":144,"name":"Karina","email":"kmuat3z@constantcontact.com","salary":"Rupiah"},
{"id":145,"name":"Alick","email":"avannar40@lycos.com","salary":"Yuan Renminbi"},
{"id":146,"name":"Giffie","email":"grossetti41@free.fr","salary":"Peso"},
{"id":147,"name":"Carmina","email":"cnowak42@canalblog.com","salary":"Euro"},
{"id":148,"name":"Brennen","email":"bcollier43@taobao.com","salary":"Peso"},
{"id":149,"name":"Kerrill","email":"kellerey44@youku.com","salary":"Yuan Renminbi"},
{"id":150,"name":"Sigismundo","email":"scater45@ihg.com","salary":"Ruble"},
{"id":151,"name":"Nehemiah","email":"nbeetlestone46@bloglovin.com","salary":"Yuan Renminbi"},
{"id":152,"name":"Gabey","email":"gtandy47@xrea.com","salary":"Yen"},
{"id":153,"name":"Nicola","email":"ntesseyman48@nasa.gov","salary":"Baht"},
{"id":154,"name":"Ardyth","email":"abeauman49@bbc.co.uk","salary":"Franc"},
{"id":155,"name":"Denise","email":"dwalkden4a@sbwire.com","salary":"Cedi"},
{"id":156,"name":"Kristoforo","email":"kreinbech4b@xrea.com","salary":"Peso"},
{"id":157,"name":"Denise","email":"dcamings4c@quantcast.com","salary":"Rupiah"},
{"id":158,"name":"Cristine","email":"ctoman4d@dot.gov","salary":"Birr"},
{"id":159,"name":"Shawn","email":"scaghan4e@ehow.com","salary":"Rupiah"},
{"id":160,"name":"Gannon","email":"ghastwall4f@posterous.com","salary":"Euro"},
{"id":161,"name":"Bernadene","email":"bdeery4g@chronoengine.com","salary":"Peso"},
{"id":162,"name":"Herta","email":"hdorre4h@theguardian.com","salary":"Rupiah"},
{"id":163,"name":"Melosa","email":"mthornebarrow4i@walmart.com","salary":"Rupiah"},
{"id":164,"name":"Corry","email":"claugier4j@nature.com","salary":"Zloty"},
{"id":165,"name":"Shaylyn","email":"ssussems4k@redcross.org","salary":"Real"},
{"id":166,"name":"Papagena","email":"pillwell4l@php.net","salary":"Peso"},
{"id":167,"name":"Colleen","email":"chamsley4m@soup.io","salary":"Peso"},
{"id":168,"name":"Tilly","email":"tserrier4n@dailymotion.com","salary":"Rupiah"},
{"id":169,"name":"Putnem","email":"pswinney4o@mozilla.org","salary":"Koruna"},
{"id":170,"name":"Nathalia","email":"nsmallshaw4p@twitpic.com","salary":"Zloty"},
{"id":171,"name":"Herbie","email":"hmcgarel4q@weebly.com","salary":"Yuan Renminbi"},
{"id":172,"name":"Sandra","email":"sthurston4r@paypal.com","salary":"Rupiah"},
{"id":173,"name":"Collin","email":"civanchenkov4s@hibu.com","salary":"Yuan Renminbi"},
{"id":174,"name":"Griffin","email":"ggorman4t@wikispaces.com","salary":"Pound"},
{"id":175,"name":"Valeda","email":"vconerding4u@youtu.be","salary":"Rial"},
{"id":176,"name":"Ina","email":"ikiera4v@hubpages.com","salary":"Peso"},
{"id":177,"name":"Madelle","email":"mmatonin4w@hexun.com","salary":"Guarani"},
{"id":178,"name":"Deanna","email":"dnoweak4x@cmu.edu","salary":"Koruna"},
{"id":179,"name":"Mallorie","email":"mmcleman4y@sbwire.com","salary":"Euro"},
{"id":180,"name":"Shirley","email":"sliggett4z@blog.com","salary":"Euro"},
{"id":181,"name":"Sharleen","email":"sjotcham50@elegantthemes.com","salary":"Somoni"},
{"id":182,"name":"Charmane","email":"ccorden51@wired.com","salary":"Franc"},
{"id":183,"name":"Marijn","email":"mbradbury52@time.com","salary":"Zloty"},
{"id":184,"name":"Irwinn","email":"imuckle53@homestead.com","salary":"Dinar"},
{"id":185,"name":"Betta","email":"blamyman54@tripadvisor.com","salary":"Yuan Renminbi"},
{"id":186,"name":"Ebonee","email":"epetcher55@biblegateway.com","salary":"Koruna"},
{"id":187,"name":"Bernarr","email":"bgrunbaum56@hc360.com","salary":"Euro"},
{"id":188,"name":"Deerdre","email":"demanson57@msu.edu","salary":"Euro"},
{"id":189,"name":"Kay","email":"kmalarkey58@cbslocal.com","salary":"Koruna"},
{"id":190,"name":"Derrek","email":"dcareless59@china.com.cn","salary":"Baht"},
{"id":191,"name":"Lynette","email":"lblinkhorn5a@histats.com","salary":"Dollar"},
{"id":192,"name":"Odele","email":"oderrington5b@ft.com","salary":"Ruble"},
{"id":193,"name":"Emmit","email":"efredi5c@slate.com","salary":"Peso"},
{"id":194,"name":"Lorrayne","email":"ldansken5d@time.com","salary":"Ruble"},
{"id":195,"name":"Rollie","email":"rwehner5e@reuters.com","salary":"Rupiah"},
{"id":196,"name":"Roselle","email":"rraunds5f@whitehouse.gov","salary":"Shilling"},
{"id":197,"name":"Karalynn","email":"kpedroli5g@businesswire.com","salary":"Yuan Renminbi"},
{"id":198,"name":"Benedikta","email":"bkerner5h@webs.com","salary":"Euro"},
{"id":199,"name":"Hazlett","email":"hbaxstar5i@ca.gov","salary":"Lari"},
{"id":200,"name":"Joshuah","email":"jadolf5j@opera.com","salary":"Ruble"}]
function students_data () {
students.map((student) => {
    let rows = " "
    for (student of students){
        rows = rows +
        `<tr>
        <td>${student.name}</td>
        <td>${student.email}</td>
        <td>${student.salary}</td>
        </tr>`
    }
    document.getElementById('abc').innerHTML=rows
})
}
